##### Converting final CSV file from Modeling.ipynb to better format for Tableau

In [1]:
import pandas as pd

In [2]:
results_dummied = pd.read_csv('/Users/wasilaq/Metis/Proj3/pickled_files/ArrivalDelayResults_dummied.csv')
all_flights = pd.read_pickle('/Users/wasilaq/Metis/Proj3/pickled_files/all_flights')

In [3]:
results_dummied.head()

,Unnamed: 0,dayofweek,operating_airline_AA,operating_airline_AS,operating_airline_B6,operating_airline_DL,operating_airline_EV,operating_airline_F9,operating_airline_G7,operating_airline_MQ,...,tail_number_N999DN,Type_None,Type_Rain,Type_Snow,arrival_delay,operating_airline_9E,tail_number_N101HQ,Type_Fog,prediction,pred_prob_delay
0,12178,6,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0.542456
1,15588,5,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0.000000
2,12073,5,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0.000000
3,26025,2,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0.003333
4,7966,5,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0.026667

In [4]:
results_dummied.columns

Index(['Unnamed: 0', 'dayofweek', 'operating_airline_AA',
       'operating_airline_AS', 'operating_airline_B6', 'operating_airline_DL',
       'operating_airline_EV', 'operating_airline_F9', 'operating_airline_G7',
       'operating_airline_MQ',
       ...
       'tail_number_N999DN', 'Type_None', 'Type_Rain', 'Type_Snow',
       'arrival_delay', 'operating_airline_9E', 'tail_number_N101HQ',
       'Type_Fog', 'prediction', 'pred_prob_delay'],
      dtype='object', length=2871)

In [11]:
results_dummied_clean = results_dummied.set_index(keys=results_dummied['Unnamed: 0']).drop(columns=['Unnamed: 0'])

In [15]:
results = all_flights[['dayofweek','operating_airline','tail_number','Type']].iloc[results_dummied_clean.index]
results['prediction'] = results_dummied_clean['prediction']
results['pred_prob_delay'] = results_dummied_clean['pred_prob_delay']

results

,dayofweek,operating_airline,tail_number,Type,prediction,pred_prob_delay
12178,6,DL,N316DN,None,1,0.542456
15588,5,DL,N303DQ,None,0,0.000000
12073,5,DL,N983DL,None,0,0.000000
26025,2,DL,N373DA,None,0,0.003333
7966,5,WN,N205WN,None,0,0.026667
...,...,...,...,...,...,...
1401,3,9E,N819AY,None,0,0.307151
26012,2,DL,N824DN,None,0,0.024121
14375,6,DL,N310DE,None,0,0.000000
18017,5,DL,N591NW,Rain,1,0.589302
4948,2,OO,N8932C,None,0,0.052952

In [16]:
results.to_csv('/Users/wasilaq/Metis/proj3/pickled_files/ArrivalDelayResults.csv')